### ISSUE TITLE
No files created with 32-bit version

### ISSUE THREAD

**Issue by gingerbeardman** [abenokobo/PDFontTool#1]
- Win 10 64-bit = works OK
- Win 7 Pro 32-bit = no files created, command returns immdiately

<img width="1024" alt="Screen shot 2022-03-09 at 11 39 37" src="https://user-images.githubusercontent.com/49612/157435280-b4705d0e-0e06-4c4f-943a-03fb1a2c2961.png">

**Comment by takuyamsc** [comment]
I checked on Windows 11 and it works correctly on the x86 version.
On Windows 7, the Direct2D version is low and may not work.

**Comment by gingerbeardman** [comment]
No problem, I will use my Win 10 VM for this.

It would be good if it did check and reported error.
