### ISSUE TITLE
Strange stray pixels and split characters at larger sizes

### ISSUE THREAD

**Issue by gingerbeardman** [abenokobo/PDFontTool#2]
Upon loading the converted font at size 52,64, maybe others... the period character has a stray pixel off to the right

Command: `pdft -R Today.ttf Output Today52 52`

TTF: [Today.ttf.zip](https://github.com/abenokobo/PDFontTool/files/8214381/Today.ttf.zip)

Caps Screenshot:
<img width="677" alt="Screen shot 2022-03-09 at 11 55 18" src="https://user-images.githubusercontent.com/49612/157437279-9edc4116-6573-4d58-9c24-56a8288c62cd.png">

**Comment by gingerbeardman** [comment]
Also a issue with this font is / character, which is split over two cells. Perhaps the same issue?

**Comment by takuyamsc** [comment]
![issue2](https://user-images.githubusercontent.com/99154032/157569031-7731c187-4a7b-4830-9eb9-a8432c0ece85.png)
The problem was caused by drawing outside the expected BOX.
Clipping solves the problem for now, but it doesn't look good.
I will look into the option of creating a margin for the BOX.

**Comment by takuyamsc** [comment]
Added clipping when drawing fonts.
Since the appearance did not change much even if some parts were not drawn due to clipping, we did not implement the margin.
