### ISSUE TITLE
glyphs too big!

### ISSUE THREAD

**Issue by jacobwhite** [abenokobo/PDFontTool#3]
I'm trying to convert this font, and I'm getting an error in the simulator console when I try to load the font: "glyphs too big!" repeated over and over.

[out.zip](https://github.com/abenokobo/PDFontTool/files/8694438/out.zip)

**Comment by takuyamsc** [comment]
I tried loading the attached file(out.zip) using Lua here and it seemed to load correctly.
`local f = playdate.graphics.font.new('file')`

If you don't mind, I'd like to know the detailed steps you took to get the error!
If Playdate has a glyph size limitation, there is only so much that PDFontTool can do, but it may be able to warn you, for example.

**Comment by jacobwhite** [comment]
I got it working eventually, there’s probably some glyphs it didn’t like, but it seems to work fine with the ones I’m using. Thanks for making this tool!

**Comment by takuyamsc** [comment]
Glad to hear the issue has been resolved!
